"use client";

import { useState } from "react";
import { BellRing, Check, ChevronDown, CircleCheck, ExternalLink, KeyRound, Save, ShieldCheck, SlidersHorizontal, Webhook } from "lucide-react";
import { PageTitle } from "@/components/ui";

function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label: string }) {
  return <button type="button" onClick={() => onChange(!checked)} className={`focus-ring relative h-6 w-11 rounded-full transition ${checked ? "bg-emerald-400" : "bg-slate-700"}`} aria-label={`${checked ? "Disable" : "Enable"} ${label}`} aria-pressed={checked}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition ${checked ? "left-6" : "left-1"}`} /></button>;
}

function IntegrationCard({ name, description, enabled, setEnabled, icon, color }: { name: string; description: string; enabled: boolean; setEnabled: (value: boolean) => void; icon: React.ReactNode; color: string }) {
  return <div className="panel-soft p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}>{icon}</span><Toggle checked={enabled} onChange={setEnabled} label={name} /></div><div className="mt-4"><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-slate-100">{name}</h3>{enabled && <span className="inline-flex items-center gap-1 text-[10px] font-medium text-emerald-300"><CircleCheck size={11} />Connected</span>}</div><p className="mt-1.5 text-xs leading-5 text-slate-500">{description}</p></div><button className="focus-ring mt-4 inline-flex items-center gap-1 text-xs font-medium text-sky-300 hover:text-sky-200">Configure <ExternalLink size={12} /></button></div>;
}

export default function SettingsPage() {
  const [slack, setSlack] = useState(true);
  const [jira, setJira] = useState(true);
  const [openAI, setOpenAI] = useState(true);
  const [pollInterval, setPollInterval] = useState("60");
  const [autoEscalation, setAutoEscalation] = useState(true);
  const [saved, setSaved] = useState(false);

  const save = () => {
    setSaved(true);
    window.setTimeout(() => setSaved(false), 2500);
  };

  return (
    <div className="animate-enter">
      <PageTitle eyebrow="Workspace configuration" title="Settings" description="Connect the tools your response team uses and tune how IncidentOps observes production." action={<button onClick={save} className="focus-ring inline-flex items-center justify-center gap-2 rounded-xl bg-sky-400 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-sky-300">{saved ? <Check size={16} /> : <Save size={16} />}{saved ? "Saved" : "Save changes"}</button>} />

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(315px,0.48fr)]">
        <div className="space-y-6">
          <section className="panel p-5 sm:p-6" aria-labelledby="integrations-heading"><div><h2 id="integrations-heading" className="text-base font-semibold text-slate-100">Integrations</h2><p className="mt-1 text-xs text-slate-500">Route alerts, enrich incidents, and use the model provider approved by your organization.</p></div><div className="mt-6 grid gap-3 md:grid-cols-3"><IntegrationCard name="Slack" description="Send incident updates and approval prompts to #ops-incidents." enabled={slack} setEnabled={setSlack} icon={<BellRing size={19} />} color="bg-violet-400/10 text-violet-300" /><IntegrationCard name="Jira" description="Create linked issues and sync resolution status automatically." enabled={jira} setEnabled={setJira} icon={<Webhook size={19} />} color="bg-sky-400/10 text-sky-300" /><IntegrationCard name="OpenAI" description="Power root-cause analysis and recommendation agents." enabled={openAI} setEnabled={setOpenAI} icon={<KeyRound size={19} />} color="bg-emerald-400/10 text-emerald-300" /></div></section>

          <section className="panel p-5 sm:p-6" aria-labelledby="response-heading"><div className="flex items-start justify-between gap-3"><div><h2 id="response-heading" className="text-base font-semibold text-slate-100">Response controls</h2><p className="mt-1 text-xs text-slate-500">Set the observation cadence and escalation behavior for this workspace.</p></div><SlidersHorizontal size={18} className="text-slate-500" /></div><div className="mt-6 divide-y divide-slate-700/40 rounded-xl border border-slate-700/50"><div className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-sm font-medium text-slate-200">Poll interval</h3><p className="mt-1 text-xs text-slate-500">How often Monitor Agent checks connected sources.</p></div><label className="relative"><span className="sr-only">Poll interval</span><select value={pollInterval} onChange={(event) => setPollInterval(event.target.value)} className="focus-ring appearance-none rounded-lg border border-slate-700/60 bg-slate-900/50 py-2 pl-3 pr-9 text-xs text-slate-300"><option value="30">Every 30 seconds</option><option value="60">Every minute</option><option value="300">Every 5 minutes</option><option value="900">Every 15 minutes</option></select><ChevronDown size={14} className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-500" /></label></div><div className="flex items-center justify-between gap-3 px-4 py-4"><div><h3 className="text-sm font-medium text-slate-200">Automatic escalation</h3><p className="mt-1 text-xs text-slate-500">Declare critical incidents when error budget policies are exceeded.</p></div><Toggle checked={autoEscalation} onChange={setAutoEscalation} label="automatic escalation" /></div><div className="flex items-center justify-between gap-3 px-4 py-4"><div><h3 className="text-sm font-medium text-slate-200">Human approval gate</h3><p className="mt-1 text-xs text-slate-500">Production recommendations always require approval.</p></div><span className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1.5 text-xs font-medium text-emerald-200"><ShieldCheck size={13} />Required</span></div></div></section>

          <section className="panel overflow-hidden" aria-labelledby="notification-heading"><div className="border-b border-slate-700/45 px-5 py-4 sm:px-6"><h2 id="notification-heading" className="text-base font-semibold text-slate-100">Notification policy</h2><p className="mt-1 text-xs text-slate-500">Who gets notified as incidents progress.</p></div><div className="divide-y divide-slate-700/35"><div className="flex items-center justify-between gap-3 px-5 py-4 sm:px-6"><div><p className="text-sm font-medium text-slate-200">Critical incident declared</p><p className="mt-1 text-xs text-slate-500">On-call lead, service owner, and #ops-incidents</p></div><span className="rounded-md bg-rose-400/10 px-2 py-1 text-[10px] font-semibold text-rose-200">Immediate</span></div><div className="flex items-center justify-between gap-3 px-5 py-4 sm:px-6"><div><p className="text-sm font-medium text-slate-200">Recommendation ready</p><p className="mt-1 text-xs text-slate-500">Assigned incident lead</p></div><span className="rounded-md bg-sky-400/10 px-2 py-1 text-[10px] font-semibold text-sky-200">In-app + Slack</span></div></div></section>
        </div>

        <aside className="space-y-6"><section className="panel relative overflow-hidden p-5 sm:p-6"><div className="absolute -right-12 -top-10 h-40 w-40 rounded-full bg-emerald-400/[0.08] blur-3xl" /><div className="relative"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300"><ShieldCheck size={20} /></span><h2 className="mt-5 text-base font-semibold text-slate-100">Workspace protected</h2><p className="mt-2 text-xs leading-5 text-slate-500">All production actions require a human approval and are recorded in the incident audit history.</p><div className="mt-5 space-y-2 rounded-xl border border-slate-700/45 bg-slate-900/35 p-3"><div className="flex items-center justify-between text-xs"><span className="text-slate-500">Audit logging</span><span className="font-medium text-emerald-300">Enabled</span></div><div className="flex items-center justify-between text-xs"><span className="text-slate-500">Data retention</span><span className="font-medium text-slate-300">90 days</span></div><div className="flex items-center justify-between text-xs"><span className="text-slate-500">Region</span><span className="font-medium text-slate-300">ap-south-1</span></div></div></div></section><section className="panel p-5 sm:p-6"><h2 className="text-base font-semibold text-slate-100">API connection</h2><p className="mt-1 text-xs leading-5 text-slate-500">The UI works with bundled demo data until an API URL is configured.</p><code className="mt-4 block overflow-x-auto rounded-lg border border-slate-700/50 bg-[#06101b] px-3 py-2.5 text-[11px] text-sky-200">NEXT_PUBLIC_API_URL</code><p className="mt-3 text-[11px] leading-5 text-slate-600">IncidentOps tries both <span className="text-slate-500">/incidents</span> and <span className="text-slate-500">/api/v1/incidents</span> for compatibility.</p></section></aside>
      </div>
    </div>
  );
}
