"use client";

import { useState, useEffect } from "react";
import { Bot, Check, CheckCircle2, ChevronDown, CircleAlert, CircleCheck, Clock3, ExternalLink, FileText, Hash, LoaderCircle, MessageSquare, Play, ShieldCheck, Sparkles, Terminal, ThumbsDown, ThumbsUp, X } from "lucide-react";
import { triggerAnalysis, submitRecommendationDecision, fetchIncidentNotifications } from "@/lib/api";
import type { Incident } from "@/lib/types";
import { AIIndicator, Avatar, SeverityBadge, StatusBadge } from "@/components/ui";
import { AIChat } from "@/components/ai-chat";
import { MultiAgentProgress } from "@/components/multi-agent-progress";
import { LiveMetrics } from "@/components/live-metrics";
import { ServiceGraph } from "@/components/service-graph";
import { IncidentReplay } from "@/components/incident-replay";
import { DecisionTree } from "@/components/decision-tree";
import { TimelineComments } from "@/components/timeline-comments";
import { useAuth } from "@/lib/auth-context";

const eventIcons = {
  detection: CircleAlert,
  update: Clock3,
  action: ShieldCheck,
  ai: Sparkles,
  resolution: CircleCheck,
};

const eventTones = {
  detection: "border-rose-400/25 bg-rose-400/10 text-rose-300",
  update: "border-sky-400/25 bg-sky-400/10 text-sky-300",
  action: "border-violet-400/25 bg-violet-400/10 text-violet-300",
  ai: "border-cyan-400/25 bg-cyan-400/10 text-cyan-300",
  resolution: "border-emerald-400/25 bg-emerald-400/10 text-emerald-300",
};

function ReportSection({ incidentId }: { incidentId: string }) {
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const generateReport = async () => {
    setLoading(true);
    try {
      // @ts-ignore
      const { fetchPostmortemReport } = await import("@/lib/api");
      const data = await fetchPostmortemReport(incidentId);
      setReport(data);
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  };

  if (!report) {
    return (
      <section className="panel p-5 sm:p-6" aria-labelledby="report-heading">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2"><FileText size={17} className="text-slate-400" /><h2 id="report-heading" className="text-base font-semibold text-slate-100">Postmortem Report</h2></div>
          <button onClick={generateReport} disabled={loading} className="focus-ring inline-flex items-center gap-2 rounded-xl bg-violet-500/20 px-3 py-2 text-xs font-medium text-violet-300 hover:bg-violet-500/30 disabled:opacity-50">
            {loading ? <LoaderCircle size={14} className="animate-spin" /> : <Sparkles size={14} />}
            {loading ? "Generating..." : "Generate AI Postmortem"}
          </button>
        </div>
      </section>
    );
  }

  return (
    <section className="panel overflow-hidden" aria-labelledby="report-heading">
      <div className="flex items-start justify-between border-b border-slate-700/45 px-5 py-5 sm:px-6">
        <div>
          <div className="flex items-center gap-2"><FileText size={17} className="text-violet-300" /><h2 id="report-heading" className="text-base font-semibold text-slate-100">Postmortem Report</h2></div>
          <p className="mt-1.5 text-xs text-slate-400">Generated by Report Agent.</p>
        </div>
        <AIIndicator label="Automated" />
      </div>
      <div className="p-5 sm:p-6 space-y-4">
        <div>
          <h3 className="text-sm font-semibold text-slate-200 mb-2">Lessons Learned</h3>
          <ul className="list-disc pl-5 space-y-2 text-sm text-slate-300">
            {report.lessons_learned?.map((lesson: string, i: number) => (
              <li key={i}>{lesson}</li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}

export function IncidentDetail({ incident, onRefetch }: { incident: Incident, onRefetch?: () => void }) {
  const [decision, setDecision] = useState<"approved" | "rejected" | null>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  
  // Replay State
  const [isReplaying, setIsReplaying] = useState(false);
  const [scrubIndex, setScrubIndex] = useState(incident.timeline.length);

  // When incident updates, update scrub index if not replaying
  useEffect(() => {
    if (!isReplaying) {
      setScrubIndex(incident.timeline.length);
    }
  }, [incident.timeline.length, isReplaying]);

  const visibleTimeline = isReplaying ? incident.timeline.slice(0, scrubIndex) : incident.timeline;
  // Artificially cut logs down based on replay progress (approximate by index percentage)
  const logLimit = isReplaying ? Math.max(1, Math.floor((scrubIndex / incident.timeline.length) * incident.logs.length)) : incident.logs.length;
  const visibleLogs = incident.logs.slice(0, logLimit);
  const [chatOpen, setChatOpen] = useState(false);
  const { user } = useAuth();
  const [notifications, setNotifications] = useState<any>(null);

  const decide = async (nextDecision: "approved" | "rejected") => {
    setSaving(true);
    const remoteSaved = await submitRecommendationDecision(incident.id, nextDecision);
    setDecision(nextDecision);
    setMessage(remoteSaved ? `Recommendation ${nextDecision} and recorded.` : `Recommendation ${nextDecision}; saved locally until the API reconnects.`);
    setSaving(false);
    if (onRefetch) onRefetch();
  };

  const handleTriggerAnalysis = async () => {
    setAnalyzing(true);
    await triggerAnalysis(incident.id);
    if (onRefetch) onRefetch();
  };

  useEffect(() => {
    if (incident.analysis || incident.status !== "investigating") {
      setAnalyzing(false);
    }
  }, [incident.analysis, incident.status]);

  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    if (analyzing || incident.status === "investigating" || incident.status === "executing") {
      interval = setInterval(() => {
        if (onRefetch) onRefetch();
      }, 3000);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [analyzing, incident.status, onRefetch]);

  // Fetch notifications when incident is resolved
  useEffect(() => {
    if (incident.status === "resolved" && !notifications) {
      fetchIncidentNotifications(incident.id).then(setNotifications);
    }
  }, [incident.status, incident.id, notifications]);

  return (
    <div className="animate-enter">
      <section className="panel overflow-hidden">
        <div className="relative overflow-hidden border-b border-slate-700/45 px-5 py-5 sm:px-7 sm:py-6">
          <div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-rose-400/[0.07] blur-3xl" />
          <div className="relative flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
            <div className="min-w-0">
              <div className="flex flex-wrap items-center gap-2"><span className="text-xs font-medium text-slate-500">{incident.id}</span><SeverityBadge severity={incident.severity} /><StatusBadge status={incident.status} /></div>
              <h1 className="mt-3 text-2xl font-semibold tracking-[-0.035em] text-slate-100 sm:text-[30px]">{incident.title}</h1>
              <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{incident.description}</p>
            </div>
            <div className="flex shrink-0 items-center gap-2">
              {incident.status === "investigating" && (
                <button disabled={analyzing} onClick={handleTriggerAnalysis} className="focus-ring inline-flex items-center gap-2 rounded-xl bg-violet-500/20 px-3 py-2 text-xs font-medium text-violet-300 hover:bg-violet-500/30 disabled:opacity-50">
                  {analyzing ? <LoaderCircle size={14} className="animate-spin" /> : <Sparkles size={14} />}
                  {analyzing ? "AI Analyzing..." : "Run AI Analysis"}
                </button>
              )}
              <button className="focus-ring inline-flex items-center gap-2 rounded-xl border border-slate-700/60 bg-slate-900/45 px-3 py-2 text-xs font-medium text-slate-300 hover:border-slate-600 hover:text-white"><MessageSquare size={14} />Notes</button><button className="focus-ring grid h-9 w-9 place-items-center rounded-xl border border-slate-700/60 bg-slate-900/45 text-slate-400 hover:border-slate-600 hover:text-white" aria-label="More incident options"><ChevronDown size={17} /></button></div>
          </div>
          
          {(() => {
            const durationStr = incident.duration;
            let durationMin = 0;
            if (durationStr.includes('h') && durationStr.includes('m')) {
              const parts = durationStr.split(' ');
              durationMin = parseInt(parts[0]) * 60 + parseInt(parts[1]);
            } else if (durationStr.includes('h')) {
              durationMin = parseInt(durationStr) * 60;
            } else if (durationStr.includes('m')) {
              durationMin = parseInt(durationStr);
            }
            const revenueLoss = `$${(durationMin * 150).toLocaleString()}`; // Base $150/min cost
            
            return (
              <div className="relative mt-6 grid gap-3 sm:grid-cols-3 xl:grid-cols-5">
                <div className="panel-soft px-3.5 py-3"><p className="eyebrow">Service</p><p className="mt-1.5 text-sm font-medium text-slate-200">{incident.service}</p></div>
            <div className="panel-soft px-3.5 py-3"><p className="eyebrow">Impact</p><p className="mt-1.5 text-sm font-medium text-slate-200">{incident.affectedUsers}</p></div>
                <div className="panel-soft px-3.5 py-3"><p className="eyebrow">Duration</p><p className="mt-1.5 text-sm font-medium text-slate-200">{incident.duration}</p></div>
                <div className="panel-soft px-3.5 py-3"><p className="eyebrow text-rose-300">Revenue Loss</p><p className="mt-1.5 text-sm font-bold text-rose-200">{revenueLoss}</p></div>
                <div className="panel-soft px-3.5 py-3"><p className="eyebrow">Incident lead</p><div className="mt-1.5 flex items-center gap-2"><Avatar name={incident.assignee} small /><span className="text-sm font-medium text-slate-200">{incident.assignee}</span></div></div>
              </div>
            );
          })()}
        </div>
        <div className="flex flex-wrap gap-2 px-5 py-3.5 sm:px-7"><span className="text-xs text-slate-500">Tags</span>{incident.tags.map((tag) => <span key={tag} className="rounded-md border border-slate-700/55 bg-slate-800/35 px-2 py-1 text-[10px] font-medium text-slate-400">#{tag}</span>)}</div>
      </section>

      <div className="mt-6 space-y-6">
        
        <ServiceGraph affectedService={incident.service} status={incident.status} />

        <IncidentReplay 
          incident={incident} 
          isActive={isReplaying} 
          onToggleActive={() => setIsReplaying(!isReplaying)} 
          onScrub={setScrubIndex} 
        />

        <section className="panel p-5 sm:p-6" aria-labelledby="timeline-heading">
          <div className="flex items-start justify-between gap-3"><div><h2 id="timeline-heading" className="text-base font-semibold text-slate-100">Timeline</h2><p className="mt-1 text-xs text-slate-500">A unified record of detection, response, and automated investigation.</p></div><span className="rounded-lg border border-slate-700/50 bg-slate-800/35 px-2 py-1 text-[10px] font-medium text-slate-400">{visibleTimeline.length} events</span></div>
          <ol className="mt-6 space-y-0">
            {visibleTimeline.map((event, index) => {
              const Icon = eventIcons[event.kind];
              return <li key={`${event.time}-${event.title}-${index}`} className="relative flex gap-4 pb-6 last:pb-0">{index < visibleTimeline.length - 1 && <span className="absolute left-[15px] top-8 h-[calc(100%-21px)] w-px bg-slate-700/55" />}<span className={`relative z-10 grid h-8 w-8 shrink-0 place-items-center rounded-lg border ${eventTones[event.kind]}`}><Icon size={15} /></span><div className="min-w-0 pt-0.5"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><h3 className="text-sm font-medium text-slate-200">{event.title}</h3><time className="text-[11px] text-slate-600">{event.time}</time></div><p className="mt-1 text-sm leading-6 text-slate-500">{event.description}</p></div></li>;
            })}
          </ol>
          
          <TimelineComments incidentId={incident.id} />
        </section>

        <LiveMetrics incidentStatus={incident.status} />

        <section className="panel overflow-hidden mt-6" aria-labelledby="logs-heading">
          <div className="flex items-start justify-between border-b border-slate-700/45 px-5 py-4 sm:px-6"><div><h2 id="logs-heading" className="text-base font-semibold text-slate-100">Logs</h2><p className="mt-1 text-xs text-slate-500">Correlated evidence selected by the Log Agent.</p></div><AIIndicator label="Correlated" /></div>
          <div className="overflow-x-auto bg-[#07121e]/70 p-1.5 sm:p-2"><div className="min-w-[670px] overflow-hidden rounded-xl border border-slate-700/45 font-mono text-[11px] leading-6"><div className="grid grid-cols-[110px_72px_130px_1fr] border-b border-slate-700/40 bg-slate-800/35 px-3 py-2 text-[10px] uppercase tracking-[0.12em] text-slate-500"><span>Time</span><span>Level</span><span>Source</span><span>Message</span></div>{visibleLogs.map((log, index) => <div key={`${log.time}-${index}`} className="grid grid-cols-[110px_72px_130px_1fr] border-b border-slate-800/70 px-3 py-2 text-slate-400 last:border-0"><span className="text-slate-600">{log.time}</span><span className={log.level === "ERROR" ? "text-rose-300" : log.level === "WARN" ? "text-amber-300" : "text-sky-300"}>{log.level}</span><span className="text-violet-200">{log.source}</span><span className="text-slate-300">{log.message}</span></div>)}</div></div>
        </section>

        {incident.analysis ? (
          <>
            <section className="panel overflow-hidden" aria-labelledby="analysis-heading">
              <div className="flex flex-col gap-3 border-b border-slate-700/45 bg-gradient-to-r from-violet-400/[0.08] to-transparent px-5 py-5 sm:flex-row sm:items-start sm:justify-between sm:px-6"><div><div className="flex items-center gap-2"><Sparkles size={17} className="text-violet-300" /><h2 id="analysis-heading" className="text-base font-semibold text-slate-100">AI Analysis</h2></div><p className="mt-1.5 text-xs text-slate-400">Synthesized from telemetry, logs, deployment history, and similar incidents.</p></div><span className="inline-flex w-fit items-center gap-1.5 rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1.5 text-xs font-semibold text-emerald-200"><CheckCircle2 size={13} />{incident.analysis.confidence}% confidence</span></div>
              <div className="p-5 sm:p-6"><p className="text-sm leading-7 text-slate-300">{incident.analysis.summary}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{incident.analysis.signals.map((signal, index) => <div key={signal} className="panel-soft p-3.5"><p className="eyebrow">Signal 0{index + 1}</p><p className="mt-2 text-xs leading-5 text-slate-300">{signal}</p></div>)}</div>
              
              {incident.analysis.evidenceChain && incident.analysis.evidenceChain.length > 0 && (
                <div className="mt-6 border-t border-slate-700/30 pt-6">
                  <h3 className="text-sm font-semibold text-slate-200 mb-3">AI Reasoning Trace</h3>
                  <DecisionTree evidenceChain={incident.analysis.evidenceChain} />
                </div>
              )}
              </div>
            </section>

            <section className="panel p-5 sm:p-6" aria-labelledby="root-cause-heading">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2"><CircleAlert size={17} className="text-amber-300" /><h2 id="root-cause-heading" className="text-base font-semibold text-slate-100">Root Cause</h2></div>
                <AIIndicator label="Autoscaled analysis" />
              </div>
              
              <div className="mt-4 flex items-center gap-4 border-b border-slate-700/40 pb-4">
                <div className="flex flex-col">
                  <span className="text-xs text-slate-500">Confidence Score</span>
                  <div className="mt-1 flex items-center gap-2">
                    <span className="text-2xl font-bold text-emerald-400">{incident.analysis.confidence}%</span>
                    <div className="h-2 w-24 overflow-hidden rounded-full bg-slate-800">
                      <div className="h-full bg-emerald-400" style={{ width: `${incident.analysis.confidence}%` }}></div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-4 rounded-xl border border-amber-400/15 bg-amber-400/[0.055] p-4"><p className="text-sm leading-7 text-amber-50/90">{incident.analysis.rootCause}</p></div>
              
              {incident.analysis.similarIncidents && incident.analysis.similarIncidents.length > 0 && (
                <div className="mt-5 pt-4 border-t border-slate-700/30">
                  <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-3">Similar Past Incidents</h3>
                  <div className="flex flex-wrap gap-2">
                    {incident.analysis.similarIncidents.map((incId) => (
                      <span key={incId} className="inline-flex items-center gap-1 rounded-md bg-slate-800/60 px-2.5 py-1 text-xs font-medium text-sky-300 ring-1 ring-inset ring-sky-400/20">
                        {incId}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </section>

            <section className="panel overflow-hidden" aria-labelledby="recommendation-heading">
              <div className="border-b border-slate-700/45 px-5 py-5 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-sky-300" /><div><h2 id="recommendation-heading" className="text-base font-semibold text-slate-100">Recommendation</h2><p className="mt-1 text-xs text-slate-500">A reversible plan is ready for human review.</p></div></div><span className={`rounded-md border px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] ${incident.analysis.recommendation.risk === "Low" ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-200" : "border-amber-400/25 bg-amber-400/10 text-amber-200"}`}>{incident.analysis.recommendation.risk} risk</span></div></div>
              <div className="p-5 sm:p-6"><p className="text-base font-medium leading-7 text-slate-100">{incident.analysis.recommendation.action}</p><p className="mt-3 text-sm leading-6 text-slate-400">{incident.analysis.recommendation.rationale}</p><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><Clock3 size={14} className="text-sky-300" />Estimated recovery <strong className="font-semibold text-slate-200">{incident.analysis.recommendation.estimatedRecovery}</strong></div>
              
              {incident.analysis.modelComparisons && incident.analysis.modelComparisons.length > 0 && (
                <div className="mt-6 border-t border-slate-700/30 pt-5">
                  <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-3">Multi-Model Consensus</h3>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    {incident.analysis.modelComparisons.map((mc, idx) => (
                      <div key={idx} className="rounded-xl border border-slate-700/50 bg-[#07121e]/50 p-3 flex flex-col justify-between">
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-xs font-medium text-slate-300">{mc.model}</span>
                          <span className={`text-[10px] font-bold ${mc.confidence >= 90 ? 'text-emerald-400' : 'text-amber-400'}`}>{mc.confidence}%</span>
                        </div>
                        <p className="text-[11px] text-slate-400 leading-4 line-clamp-2">{mc.action}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              </div>
            </section>

            <section className="panel p-5 sm:p-6" aria-labelledby="approval-heading">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><FileText size={17} className="text-slate-400" /><h2 id="approval-heading" className="text-base font-semibold text-slate-100">Approve or reject</h2></div><p className="mt-1.5 max-w-xl text-xs leading-5 text-slate-500">Approval executes the staged plan through your configured automation. Rejection keeps the incident open and records your decision.</p></div><div className="flex shrink-0 flex-wrap gap-2">{decision ? <span className={`inline-flex items-center gap-2 rounded-xl border px-3.5 py-2.5 text-sm font-medium ${decision === "approved" ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-200" : "border-rose-400/25 bg-rose-400/10 text-rose-200"}`}>{decision === "approved" ? <Check size={16} /> : <X size={16} />}Recommendation {decision}</span> : <><button disabled={saving} onClick={() => void decide("rejected")} className="focus-ring inline-flex items-center gap-2 rounded-xl border border-rose-400/25 bg-rose-400/[0.06] px-3.5 py-2.5 text-sm font-semibold text-rose-200 transition hover:bg-rose-400/15 disabled:cursor-wait"><ThumbsDown size={16} />Reject</button><button disabled={saving} onClick={() => void decide("approved")} className="focus-ring inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-3.5 py-2.5 text-sm font-semibold text-emerald-950 transition hover:bg-emerald-300 disabled:cursor-wait">{saving ? <LoaderCircle size={16} className="animate-spin" /> : <ThumbsUp size={16} />}Approve plan</button></>}</div></div>
              {message && <p className="mt-4 rounded-lg border border-slate-700/55 bg-slate-800/30 px-3 py-2 text-xs text-slate-400">{message}</p>}
            </section>
          </>
        ) : (
          <section className="mt-8">
            <MultiAgentProgress 
              incidentId={incident.id}
              incidentStatus={incident.status} 
              onComplete={() => {
                // If it was just triggered to investigate, maybe reload after a few seconds or when done
                if (incident.status === "investigating") {
                  setTimeout(() => window.location.reload(), 1500);
                }
              }} 
            />
          </section>
        )}

        {/* ── Execution & Verification Panel (Steps 11-12) ── */}
        {incident.timeline.some((e) => e.description?.includes("Executed:") || e.description?.includes("kubectl")) && (
          <section className="panel overflow-hidden" aria-labelledby="execution-heading">
            <div className="flex items-start justify-between border-b border-slate-700/45 bg-gradient-to-r from-orange-400/[0.06] to-transparent px-5 py-5 sm:px-6">
              <div>
                <div className="flex items-center gap-2"><Terminal size={17} className="text-orange-300" /><h2 id="execution-heading" className="text-base font-semibold text-slate-100">Execution & Verification</h2></div>
                <p className="mt-1.5 text-xs text-slate-400">Remediation command executed after human approval. Health verified by Monitor Agent.</p>
              </div>
              <span className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1.5 text-xs font-semibold text-emerald-200"><CheckCircle2 size={13} />Verified</span>
            </div>
            <div className="p-5 sm:p-6 space-y-4">
              {incident.timeline.filter((e) => e.description?.includes("Executed:") || e.description?.includes("kubectl")).map((e, i) => (
                <div key={`exec-${i}`} className="rounded-xl border border-slate-700/45 bg-[#07121e]/70 p-4">
                  <div className="flex items-center gap-2 text-xs font-medium text-orange-200 mb-2"><Play size={13} />Command Executed</div>
                  <code className="block font-mono text-xs text-emerald-300 bg-slate-900/50 rounded-lg px-3 py-2">{e.description}</code>
                </div>
              ))}
              {incident.timeline.filter((e) => e.description?.includes("Health:")).map((e, i) => (
                <div key={`verify-${i}`} className="rounded-xl border border-emerald-400/15 bg-emerald-400/[0.04] p-4">
                  <div className="flex items-center gap-2 text-xs font-medium text-emerald-200 mb-2"><ShieldCheck size={13} />Post-Fix Health Check</div>
                  <p className="text-sm text-emerald-100/90">{e.description}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* ── Notifications Panel (Steps 14-15) ── */}
        {notifications && (notifications.slack_messages?.length > 0 || notifications.jira_tickets?.length > 0) && (
          <section className="panel overflow-hidden" aria-labelledby="notifications-heading">
            <div className="flex items-start justify-between border-b border-slate-700/45 px-5 py-5 sm:px-6">
              <div>
                <div className="flex items-center gap-2"><MessageSquare size={17} className="text-sky-300" /><h2 id="notifications-heading" className="text-base font-semibold text-slate-100">Notifications</h2></div>
                <p className="mt-1.5 text-xs text-slate-400">Slack messages and Jira tickets created by the Communicator Agent.</p>
              </div>
              <AIIndicator label="Automated" />
            </div>
            <div className="p-5 sm:p-6 space-y-4">
              {notifications.slack_messages?.map((msg: any) => (
                <div key={msg.id} className="rounded-xl border border-slate-700/45 bg-[#07121e]/70 p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="grid h-7 w-7 place-items-center rounded-lg bg-[#4A154B] text-white text-xs font-bold">#</span>
                    <span className="text-xs font-medium text-slate-300">{msg.channel}</span>
                    <span className="ml-auto rounded-md bg-emerald-400/10 px-2 py-0.5 text-[10px] font-medium text-emerald-200">{msg.status}</span>
                  </div>
                  <pre className="whitespace-pre-wrap text-xs leading-5 text-slate-400 font-mono">{msg.message}</pre>
                </div>
              ))}
              {notifications.jira_tickets?.map((ticket: any) => (
                <div key={ticket.id} className="rounded-xl border border-slate-700/45 bg-[#07121e]/70 p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="grid h-7 w-7 place-items-center rounded-lg bg-[#0052CC] text-white text-xs font-bold">J</span>
                    <span className="text-sm font-semibold text-sky-200">{ticket.issue_key}</span>
                    <span className="ml-auto rounded-md bg-sky-400/10 px-2 py-0.5 text-[10px] font-medium text-sky-200">{ticket.status}</span>
                  </div>
                  <p className="text-xs text-slate-400">{ticket.summary}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* ── Postmortem Report (Step 26) ── */}
        {incident.status === "resolved" && (
          <ReportSection incidentId={incident.id} />
        )}

        <section className="panel p-5 sm:p-6" aria-labelledby="audit-heading">
          <div className="flex items-center gap-2"><FileText size={17} className="text-slate-400" /><div><h2 id="audit-heading" className="text-base font-semibold text-slate-100">Audit History</h2><p className="mt-1 text-xs text-slate-500">An immutable record of humans and agents involved in this response.</p></div></div>
          <div className="mt-5 divide-y divide-slate-700/35 rounded-xl border border-slate-700/45"><div className="grid grid-cols-[68px_minmax(110px,0.8fr)_minmax(130px,1fr)_minmax(0,2fr)] gap-3 bg-slate-800/30 px-3 py-2.5 text-[10px] uppercase tracking-[0.1em] text-slate-500 sm:px-4"><span>Time</span><span>Actor</span><span>Action</span><span>Detail</span></div>{incident.auditHistory.map((event, index) => <div key={`${event.time}-${event.action}-${index}`} className="grid grid-cols-[68px_minmax(110px,0.8fr)_minmax(130px,1fr)_minmax(0,2fr)] gap-3 px-3 py-3 text-xs sm:px-4"><span className="text-slate-600">{event.time}</span><span className="font-medium text-slate-300">{event.actor}</span><span className="text-slate-400">{event.action}</span><span className="text-slate-500">{event.detail}</span></div>)}</div>
        </section>
      </div>
      
      {/* Ask AI Floating Button */}
      {!chatOpen && (
        <button
          onClick={() => setChatOpen(true)}
          className="fixed bottom-6 right-6 z-40 flex items-center gap-2 rounded-full bg-sky-500 px-4 py-3 text-sm font-semibold text-white shadow-xl shadow-sky-500/25 transition hover:bg-sky-400 hover:-translate-y-1 hover:shadow-sky-400/30"
        >
          <Bot size={18} />
          Ask AI
        </button>
      )}

      {/* AI Chat Component */}
      {chatOpen && <AIChat incidentId={incident.id} onClose={() => setChatOpen(false)} />}
    </div>
  );
}
