"""Initial migration

Revision ID: 2033c0d5df9e
Revises:
Create Date: 2026-07-24 22:14:36.795708

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2033c0d5df9e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
