"""Add evidence_chain

Revision ID: a084df07205d
Revises: 2033c0d5df9e
Create Date: 2026-07-31 18:50:51.902718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a084df07205d'
down_revision: Union[str, Sequence[str], None] = '2033c0d5df9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('evidence_chain', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('similar_incidents', sa.Text(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=256), nullable=False))
    op.drop_column('ai_recommendations', 'similar_incidents')
    op.drop_column('ai_recommendations', 'evidence_chain')
    # ### end Alembic commands ###
